all:
	g++ -o gifWrite Main.cpp WriteGIF.cpp -I. -Wall -Wno-multichar -O3 -std=c++11
test:	
	g++ -o gifWrite Main.cpp WriteGIF.cpp -I. -Wall -Wno-multichar -O3 -std=c++11
	./gifWrite
example:
	g++ -o gifWrite Main.cpp WriteGIF.cpp -I. -Wall -Wno-multichar -O3 -std=c++11
	./gifWrite example.ssp
clean:
	rm *.gif gifWrite